### ISSUE TITLE
Feature 1 - User can Generate a Fox

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/Front-End-Project#1]
## 💰 Motivation

People want the joy of randomly generating foxes.

## 📐 Plan

Create a page where the user can generate fox images.

## 🖼️ Wireframes

![fox randomizer main page](https://github.com/user-attachments/assets/dc62b783-400b-4391-a8c7-208cc86a7a41)

## ✅ Task List
- [x] Write HTML to get basic elements on the screen.
- [x] Write CSS to style the page
- [x] Make sure things look good for mobile & pc
- [x] Write functions to obtain randomized fox image from the api for the `generate` button + create message
- [x] Create a save fox modal for later usage
- [x] Review & adjust HTML / CSS as necessary
- [x] Test application / fix any errors
