### ISSUE TITLE
Feature 2 - Save and View Foxes

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/Front-End-Project#3]
## 💰 Motivation

People want to save and view their lovely foxes.

## 📐 Plan

Create a page where the user can view their fox images and add functionality to the save fox modal.

## 🖼️ Wireframes

![view foxes page](https://github.com/user-attachments/assets/eb4d2deb-a0c9-4b08-8cdf-ea7bbfbb2246)

## ✅ Task List
- [x] create data object in `data.ts`
- [x] write functions to read & write data from local storage
- [x] write a function for page swapping & allow user to swap pages
- [x] create the page where users can view foxes
- [x] add functionality to the save fox modal
  - [x] add event listener to the `yes` button so that the image and inputted data get added to the foxes page & the data object
  - [x] reset fox image and message to their defaults
- [x] Review & adjust HTML / CSS as necessary
- [x] Test application / fix any errors
