### ISSUE TITLE
Feature 3 - User Can Edit Fox

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/Front-End-Project#5]
## 💰 Motivation

People want to make edits to their cute foxes.

## 📐 Plan

Create a page where the user can edit their fox images and add functionality to allow them to do so.

## 🖼️ Wireframes

![edit fox page](https://github.com/user-attachments/assets/e7fb859d-1d05-4958-826b-2009ca5540c5)

## ✅ Task List
- [x] create an edit fox page
- [x] allow the user to navigate to the edit page by clicking on the pencil icon w/ the correct info populated on the edit page
- [x] add functionality to the save button
- [x] add error checking if user attempts to save w/ empty title & notes
- [x] Review & adjust HTML / CSS as necessary
- [x] Test application / fix any errors
