### ISSUE TITLE
Feature 4 - User Can Delete Fox

### ISSUE THREAD

**Issue by MitchellMaliglig** [MitchellMaliglig/Front-End-Project#7]
## 💰 Motivation

People want to delete their foxes (for some reason).

## 📐 Plan

Create a delete fox modal that allows for deletion, then add the functionality for the operation to happen.

## 🖼️ Wireframes

https://www.figma.com/design/mZgJSm19ICpB3JmiKJJs63/Mitchell-Maliglig---Front-End-Project?node-id=235-1791&t=KqeZRgNzsp6LX9jx-0

## ✅ Task List
- [x] create a delete fox modal & add navigation to delete fox anchor
- [x] add functionality to the delete fox modal 
  - [x] write function to remove the correct fox from the data object
  - [x] write the event listener to carry out deletion from the DOM
- [x] Review & adjust HTML / CSS as necessary
- [x] Test application / fix any errors
